/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DOMOTICS 9999
#define DOMOTICS_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define sendData 1
extern  bool_t * senddata_2(char **, CLIENT *);
extern  bool_t * senddata_2_svc(char **, struct svc_req *);
extern int domotics_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sendData 1
extern  bool_t * senddata_2();
extern  bool_t * senddata_2_svc();
extern int domotics_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
